services:

  database:
    container_name: database
    build:
      context: ./database
      dockerfile: database.Dockerfile
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - dockernetw

  geoserver:
    container_name: geoserver
    build:
      context: ./geoserver
      dockerfile: geoserver.Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
      - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
    depends_on:
      - database
    networks:
      - dockernetw

#   util:
#     container_name: util
#     build:
#       context: ./util
#       dockerfile: util.Dockerfile
#     restart: no
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock
#     depends_on:
#       - geoserver
#     networks:
#       - dockernetw

networks:
  dockernetw:
    driver: bridge



